package com.speearth.view.gestisciclienti.schermate.componenti.form;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.DatePicker;

public class AggiungiClienteForm {
	@FXML
	private TextField input_nome;
	@FXML
	private TextField input_cognome;
	@FXML
	private DatePicker input_data_nascita;
	@FXML
	private Button bottone_aggiungi;
	@FXML
	private TextField input_codice_fiscale;

	// Event Listener on Button[#bottone_aggiungi].onAction
	@FXML
	public void ricercaBiglietti(ActionEvent event) {
		// TODO Autogenerated
	}
}
