package com.speearth.view.gestisciclienti.schermate;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.TableView;

public class GesticiClientiView {
	@FXML
	private AnchorPane form_container;
	@FXML
	private TableView tabella_clienti;
	@FXML
	private TextField input_chiave_ricerca;
	@FXML
	private Button bottone_torna_alla_home;

	// Event Listener on Button[#bottone_torna_alla_home].onAction
	@FXML
	public void vaiAllaHome(ActionEvent event) {
		// TODO Autogenerated
	}
}
