package com.speearth.view.creaofferta.schermate;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class CreaOffertaView {
	@FXML
	private Button bottone_torna_alla_home;
	@FXML
	private Button bottone_ricerca;
	@FXML
	private Button bottone_riepilogo;
	@FXML
	private Button bottone_svuota;
	@FXML
	private Button bottone_conferma;
	@FXML
	private TableView tabella_pacchetto;
	@FXML
	private TableColumn tipo_servizio_col;
	@FXML
	private TableColumn fornitore_servizio_col;
	@FXML
	private TableColumn prezzo_servizio_col;
	@FXML
	private AnchorPane biglietto_form_container;
	@FXML
	private ListView lista_risultati_biglietti;
	@FXML
	private AnchorPane alloggio_form_container;
	@FXML
	private ListView lista_risultati_alloggi;

	// Event Listener on Button[#bottone_torna_alla_home].onAction
	@FXML
	public void vaiAScegliServizio(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bottone_riepilogo].onAction
	@FXML
	public void vaiARiepilogo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bottone_svuota].onAction
	@FXML
	public void svuotaPacchetto(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bottone_conferma].onAction
	@FXML
	public void confermaPacchetto(ActionEvent event) {
		// TODO Autogenerated
	}
}
