package com.speearth.view.prenotaservizio;

import java.util.ArrayList;
import java.util.HashMap;

import com.speearth.controller.AppFacadeController;
import com.speearth.model.core.Alloggio;
import com.speearth.model.core.IServizioComponent;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.ListView;
import javafx.scene.control.MenuButton;
import javafx.scene.control.TextField;

public class RicercaAloggioView {
	@FXML
	private TextField input_localita;
	@FXML
	private DatePicker input_data_arrivo;
	@FXML
	private DatePicker input_data_partenza;
	@FXML
	private Button ricerca_alloggi;
	@FXML
	private MenuButton input_numero_singole;
	@FXML
	private MenuButton input_ora_partenza;
	@FXML
	private MenuButton input_ora_arrivo;
	@FXML
	private CheckBox input_singola;
	@FXML
	private CheckBox input_doppia;
	@FXML
	private CheckBox input_tripla;
	@FXML
	private CheckBox input_quadrupla;
	@FXML
	private MenuButton input_numero_doppie;
	@FXML
	private MenuButton input_numero_triple;
	@FXML
	private MenuButton input_numero_quadruple;
	@FXML
	private Button bottone_scegli_servizio;
	@FXML
	private Button bottone_ricerca;
	@FXML
	private Button bottone_riepilogo;
	@FXML
	private ListView<RisultatoAlloggioView> lista_risultati;
	
	/**
	 * Recupera i dati inseriti dall'Utente nella form di ricerca
	 * 
	 * @return HashMap<String, String>
	 */
	private HashMap<String, String> recuperaDati() {
		HashMap<String, String> parametri = new HashMap<String, String>();
		parametri.put("data_arrivo", this.input_data_arrivo.toString());
		parametri.put("data_partenza", this.input_data_partenza.toString());
		parametri.put("stanza_doppia", this.input_doppia.getText());
		parametri.put("località", this.input_localita.getText());
		parametri.put("numero_doppie", this.input_numero_doppie.getText());
		parametri.put("numero_quadruple", this.input_numero_quadruple.getText());
		parametri.put("numero_singole", this.input_numero_singole.getText());
		parametri.put("numero_triple", this.input_numero_triple.getText());
		parametri.put("ora_arrivo", this.input_ora_arrivo.getText());
		parametri.put("ora_partenza", this.input_ora_partenza.getText());
		parametri.put("stanza_quadrupla", this.input_quadrupla.getText());
		parametri.put("stanza_singola", this.input_singola.getText());
		parametri.put("stanza_tripla", this.input_tripla.getText());
		return parametri;
	}


	// Event Listener on Button[#ricerca_alloggi].onAction
	@FXML
	public void ricercaAlloggi(ActionEvent event) {
		ArrayList<IServizioComponent> risultati = AppFacadeController.getInstance().getPrenotaServizioController()
				.getPrenotaAlloggioController().ricerca(this.recuperaDati());
		
		ObservableList<RisultatoAlloggioView> lista = FXCollections.observableArrayList();
		for (IServizioComponent alloggio : risultati) {
			lista.add(new RisultatoAlloggioView((Alloggio) alloggio));
		}
		this.lista_risultati.setItems(lista);
	}

	// Event Listener on Button[#bottone_scegli_servizio].onAction
	@FXML
	public void vaiAScegliServizio(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#bottone_ricerca].onAction
	@FXML
	public void vaiARicerca(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#bottone_riepilogo].onAction
	@FXML
	public void vaiARiepilogo(ActionEvent event) {
		// TODO Autogenerated
	}
}
