package com.speearth.view.prenotaservizio;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Optional;
import java.util.ResourceBundle;

import com.speearth.controller.AppFacadeController;
import com.speearth.controller.PrenotaAlloggioController;
import com.speearth.model.core.Alloggio;
import com.speearth.model.core.IServizioComponent;
import com.speearth.utility.Costanti;
import com.speearth.view.View;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.CheckBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.ListView;
import javafx.scene.control.MenuButton;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;

public class RicercaAlloggioView extends View {
	@FXML
	private TextField input_localita;
	@FXML
	private DatePicker input_data_arrivo;
	@FXML
	private DatePicker input_data_partenza;
	@FXML
	private Button ricerca_alloggi;
	@FXML
	private MenuButton input_numero_singole;
	@FXML
	private MenuButton input_ora_partenza;
	@FXML
	private MenuButton input_ora_arrivo;
	@FXML
	private CheckBox input_singola;
	@FXML
	private CheckBox input_doppia;
	@FXML
	private CheckBox input_tripla;
	@FXML
	private CheckBox input_quadrupla;
	@FXML
	private MenuButton input_numero_doppie;
	@FXML
	private MenuButton input_numero_triple;
	@FXML
	private MenuButton input_numero_quadruple;
	@FXML
	private Button bottone_scegli_servizio;
	@FXML
	private Button bottone_ricerca;
	@FXML
	private Button bottone_riepilogo;
	@FXML
	private ListView<Alloggio> lista_risultati;

	private ObservableList<Alloggio> lista_alloggi = FXCollections.observableArrayList();

	private PrenotaAlloggioController controller;

	/**
	 * Recupera i dati inseriti dall'Utente nella form di ricerca
	 * 
	 * @return HashMap<String, String>
	 */
	private HashMap<String, String> recuperaDati() throws NullPointerException {
		HashMap<String, String> parametri = new HashMap<String, String>();

		parametri.put("data_arrivo", this.input_data_arrivo.toString());
		parametri.put("data_partenza", this.input_data_partenza.toString());
		parametri.put("stanza_doppia", this.input_doppia.getText());
		parametri.put("località", this.input_localita.getText());
		parametri.put("numero_doppie", this.input_numero_doppie.getText());
		parametri.put("numero_quadruple", this.input_numero_quadruple.getText());
		parametri.put("numero_singole", this.input_numero_singole.getText());
		parametri.put("numero_triple", this.input_numero_triple.getText());
		parametri.put("ora_arrivo", this.input_ora_arrivo.getText());
		parametri.put("ora_partenza", this.input_ora_partenza.getText());
		parametri.put("stanza_quadrupla", this.input_quadrupla.getText());
		parametri.put("stanza_singola", this.input_singola.getText());
		parametri.put("stanza_tripla", this.input_tripla.getText());

		return parametri;
	}

	/**
	 * Inizializza la classe
	 * 
	 * @param arg0
	 * @param arg1
	 */
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		this.controller = AppFacadeController.getInstance().getPrenotaServizioController()
				.getPrenotaAlloggioController();
		this.lista_risultati.setItems(this.lista_alloggi);
		this.lista_risultati.setCellFactory(param -> new RicercaAlloggioListView());
	}

	// Event Listener on Button[#ricerca_alloggi].onAction
	@FXML
	public void ricercaAlloggi(ActionEvent event) {
		try {
			HashMap<String, String> dati = this.recuperaDati();
			ArrayList<IServizioComponent> risultati = this.controller.ricerca(dati);

			this.lista_alloggi.clear();

			for (int i = 0; i < risultati.size(); i++)
				this.lista_alloggi.add((Alloggio) risultati.get(i));

			this.lista_risultati.setItems(lista_alloggi);

		} catch (NullPointerException e) {
			e.printStackTrace();
			mostraAlert(AlertType.ERROR, Costanti.TITOLO_ERRORE, Costanti.MESSAGGIO_PARAMETRI_MANCANTI);
		}
	}

	// Event Listener on Button[#bottone_scegli_servizio].onAction
	@FXML
	public void vaiAScegliServizio(ActionEvent event) throws IOException {
		Alert alert = new Alert(AlertType.CONFIRMATION);
		alert.setTitle(Costanti.TITOLO_TORNA_A_SCEGLI_SERVIZIO);
		alert.setHeaderText(Costanti.MESSAGGIO_TORNA_A_SCELTA_SERVIZIO);

		Optional<ButtonType> result = alert.showAndWait();
		if (result.get() == ButtonType.OK) {
			this.cambiaScena(event, Costanti.TITOLO_SCEGLI_SERVIZIO, Costanti.FXML_SCEGLI_SERVIZIO);
		} else {
			alert.close();
		}
	}

	// Event Listener on Button[#bottone_ricerca].onAction
	@FXML
	public void vaiARicerca(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#bottone_riepilogo].onAction
	@FXML
	public void vaiARiepilogo(ActionEvent event) throws IOException {
		if (AppFacadeController.getInstance().getPrenotaServizioController().getServizio() == null) {
			Alert alert = new Alert(AlertType.ERROR);
			alert.setTitle(Costanti.TITOLO_NESSUN_SERVIZIO);
			alert.setHeaderText(Costanti.MESSAGGIO_NESSUN_SERVIZIO);
			alert.showAndWait();
		} else
			this.cambiaScena(event, Costanti.TITOLO_RIEPILOGO, Costanti.FXML_RIEPILOGO);
	}
}
