package com.speearth.view.prenotaservizio;

import java.awt.TextField;

import com.speearth.controller.AppFacadeController;
import com.speearth.model.core.Cliente;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.Label;

public class RiepilogoView {
	@FXML
	private Button bottone_scegli_servizio;
	@FXML
	private Button bottone_ricerca;
	@FXML
	private Button bottone_riepilogo;
	@FXML
	private TextField input_codice_tessera;
	@FXML
	private Label output_nome_cliente;
	@FXML
	private Label output_cognome_cliente;
	@FXML
	private Label output_data_nascita_cliente;
	@FXML
	private Label output_cf_cliente;
	@FXML
	private Button bottone_identifica_cliente;
	@FXML
	private Label output_totale;
	@FXML
	private Button bottone_conferma_pagamento;
	@FXML
	private Label input_metodo_pagamento;

	private Cliente cliente = null;

	private void impostaInfoCliente(Cliente cliente) {
		this.output_cf_cliente.setText(cliente.getCodiceFiscale());
		this.output_cognome_cliente.setText(cliente.getCognome());
		this.output_data_nascita_cliente.setText(cliente.getDataNascita().toString());
		this.output_nome_cliente.setText(cliente.getNome());
	}

	// Event Listener on Button[#bottone_scegli_servizio].onAction
	@FXML
	public void vaiAScegliServizio(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#bottone_ricerca].onAction
	@FXML
	public void vaiARicerca(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#bottone_riepilogo].onAction
	@FXML
	public void vaiARiepilogo(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#bottone_identifica_cliente].onAction
	@FXML
	public void identificaCliente(ActionEvent event) {
		this.cliente = AppFacadeController.getInstance().getPrenotaServizioController()
				.identificaCliente(this.input_codice_tessera.getText());
		if (cliente != null)
			this.impostaInfoCliente(cliente);
		else {
			Alert alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Cliente non trovato");
			alert.setContentText("Non è stato trovato alcun Cliente con questo codice Tessera.");
			alert.showAndWait();
		}
	}

	// Event Listener on Button[#bottone_conferma_pagamento].onAction
	@FXML
	public void effettuaPagamento(ActionEvent event) {
		String ricevuta = AppFacadeController.getInstance().getPrenotaServizioController().effettuaPagamento(this.cliente,
				this.input_metodo_pagamento.getText());
		Alert alert = new Alert(AlertType.INFORMATION);
		alert.setTitle("Pagamento effettuato");
		alert.setHeaderText("Il Pagamento è andato a buon fine!");
		alert.setContentText(ricevuta);
		alert.showAndWait();
	}
}
