package com.speearth.view.prenotaservizio;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.input.MouseEvent;

public class RisultatoAlloggioView {
	@FXML
	private Label output_data_arrivo;
	@FXML
	private Label output_ora_arrivo;
	@FXML
	private Label output_data_partenza;
	@FXML
	private Label output_ora_partenza;
	@FXML
	private ListView<Label> output_stanze;
	@FXML
	private Label output_localita;
	@FXML
	private Label output_nome_fornitore;
	@FXML
	private Button bottone_annulla;
	@FXML
	private Button bottone_conferma;
	@FXML
	private Label output_prezzo;

	// Event Listener on BorderPane.onMouseClicked
	@FXML
	public void selezionaBiglietto(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#bottone_annulla].onAction
	@FXML
	public void deselezionaAlloggio(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#bottone_conferma].onAction
	@FXML
	public void confermaAlloggio(ActionEvent event) {
		// TODO Autogenerated
	}
}
