package com.speearth.view.prenotaservizio;

import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Set;

import com.speearth.model.core.Alloggio;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.BorderPane;

public class RisultatoAlloggioView {
	@FXML
	private BorderPane risultato_alloggio;
	@FXML
	private Label output_data_arrivo;
	@FXML
	private Label output_ora_arrivo;
	@FXML
	private Label output_data_partenza;
	@FXML
	private Label output_ora_partenza;
	@FXML
	private ListView<String> output_stanze;
	@FXML
	private Label output_localita;
	@FXML
	private Label output_nome_fornitore;
	@FXML
	private Button bottone_annulla;
	@FXML
	private Button bottone_conferma;
	@FXML
	private Label output_prezzo;
	
	/**
	 * Costruttore con parametro
	 * 
	 * @param alloggio
	 */
	public RisultatoAlloggioView() {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/ui/fxml/RisultatoAlloggio.fxml"));
			loader.setController(this);
			loader.load();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * Imposta nelle Label i dati dell'alloggio
	 * 
	 * @param alloggio
	 */
	public void impostaInfo(Alloggio alloggio) {
		this.output_data_arrivo.setText(alloggio.getDataArrivo().format(DateTimeFormatter.ISO_DATE));
		this.output_ora_arrivo.setText(alloggio.getDataArrivo().format(DateTimeFormatter.ISO_TIME));
		this.output_data_partenza.setText(alloggio.getDataPartenza().format(DateTimeFormatter.ISO_DATE));
		this.output_ora_partenza.setText(alloggio.getDataPartenza().format(DateTimeFormatter.ISO_TIME));
		this.output_localita.setText(alloggio.getLocalita().toString());
		this.output_nome_fornitore.setText(alloggio.getFornitore().toString());
		this.output_prezzo.setText(Float.toString(alloggio.getPrezzo()));
		this.output_prezzo.setText(Float.toString(alloggio.getPrezzo()) + " €");
		
		HashMap<String, Integer> stanze = alloggio.getStanze();
		Set<String> tipi_stanze = stanze.keySet();
		ArrayList<String> rooms = new ArrayList<String>();
		
		for (String tipo : tipi_stanze)
			rooms.add(tipo + ": " + stanze.get(tipo));
		
		ObservableList<String> observableRooms = FXCollections.observableArrayList();
		observableRooms.setAll(rooms);
		this.output_stanze.setItems(observableRooms);
	}

	// Event Listener on BorderPane.onMouseClicked
	@FXML
	public void selezionaBiglietto(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#bottone_annulla].onAction
	@FXML
	public void deselezionaAlloggio(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#bottone_conferma].onAction
	@FXML
	public void confermaAlloggio(ActionEvent event) {
		// TODO Autogenerated
	}
	
	/**
	 * Restituisce il border pane
	 */
	public BorderPane getBorderPane() {
		return risultato_alloggio;
	}
}
