package com.speearth.view.prenotaservizio;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.input.MouseEvent;

public class RisultatoBigliettoView {
	@FXML
	private Label output_partenza_andata;
	@FXML
	private Label output_data_partenza_andata;
	@FXML
	private Label output_ora_partenza_andata;
	@FXML
	private Label output_destinazione_andata;
	@FXML
	private Label output_data_destinazione_andata;
	@FXML
	private Label output_ora_destinazione_andata;
	@FXML
	private Label output_n_adulti_andata;
	@FXML
	private Label output_n_bambini_andata;
	@FXML
	private Label output_partenza_ritorno;
	@FXML
	private Label output_data_partenza_ritorno;
	@FXML
	private Label output_ora_partenza_ritorno;
	@FXML
	private Label output_destinazione_ritorno;
	@FXML
	private Label output_data_destinazione_ritorno;
	@FXML
	private Label output_ora_destinazione_ritorno;
	@FXML
	private Label output_n_adulti_ritorno;
	@FXML
	private Label output_n_bambini_ritorno;
	@FXML
	private Label output_nome_fornitore;
	@FXML
	private Button bottone_annulla;
	@FXML
	private Button bottone_conferma;
	@FXML
	private Label output_prezzo;

	// Event Listener on BorderPane.onMouseClicked
	@FXML
	public void selezionaBiglietto(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#bottone_annulla].onAction
	@FXML
	public void deselezionaBiglietto(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#bottone_conferma].onAction
	@FXML
	public void confermaBiglietto(ActionEvent event) {
		// TODO Autogenerated
	}
}
