package com.speearth.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

public class HomeResponsabileOfferteView extends View{
	@FXML
	private Button bottone_prenota_servizio;
	@FXML
	private Button bottone_gestici_clienti;
	@FXML
	private Button bottone_crea_offerta;

	public HomeResponsabileOfferteView(Stage stage) {
		// TODO Auto-generated constructor stub
	}
	// Event Listener on Button[#bottone_prenota_servizio].onAction
	@FXML
	public void prenotaServizio(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bottone_gestici_clienti].onAction
	@FXML
	public void gesticiClienti(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bottone_crea_offerta].onAction
	@FXML
	public void creaOfferta(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
	@Override
	public String getResourceName() {
		// TODO Auto-generated method stub
		return null;
	}
}
